type Geo = [number | string, number | string];

type Listing = {
  _id: "5bc29c570d4dc8b548dcda43";
  ListingID: "18591592";
  MLSNumber: "SK704730";
  OrganizationIDs: "129277";
  Latitude: "53.2513";
  Longitude: "-105.7616";
  Address: "Lot 3 Park Meadow LN";
  City: "Buckland Rm No. 491";
  HasAcreage: "1";
  HasAirConditioning: "1";
  AmenitiesNearby: null;
  Bathrooms: "3";
  Bedrooms: "6";
  BuildingAmenities: null;
  BuildingType: "1";
  BusinessType: null;
  ClearCeilingHeight: null;
  Community: null;
  ConstructionStyle: null;
  Features: "1,42,126,256";
  HasFireplace: "1";
  HasGarage: "1";
  LandSizeMin: "10521.8267";
  LandSizeMax: "10521.8267";
  LeasePrice: null;
  LoadingType: null;
  ParkingSpaces: "11";
  HasPool: "0";
  SalePrice: "975000.0000";
  PropertyType: "300";
  SizeExterior: null;
  SizeInterior: "5300.0000";
  StoriesMin: "2.0000";
  StoriesMax: "2.0000";
  PropertyViewType: null;
  HasVirtualTour: "0";
  HasWaterfront: "1";
  ZoningType: null;
  InsertedDate: "1504025493";
  ListingLastUpdated: "2018-04-05 14:53:33.773";
  PostalCode: "s6v5r3";
  CropType: null;
  FarmType: null;
  LivestockType: null;
  LandUseType: null;
  BusinessSubType: null;
  UtilitiesAvailable: null;
  IndividualIDs: "1930812";
  Keywords: "Living is easy in this impressive generously spacious acreage located in quiet Park Meadow estates only 3 minutes north of Prince Albert This beautiful cul de sac of acreages has a man made lake and pavement through out providing an excellent walking biking or running path year round The open floor plan encompasses 6 spacious bedrooms with plenty of room for study sleep and storage 3 luxurious bathrooms and a sleek and stylish gourmet kitchen that flows through to the dining and living room areas the dining room opens up to a spacious rear screened in 3 season sun room overlooking the privately treed back yard The Master bedroom complete with a walkin closet and ensuite ensures parents have plenty of private space All closets have been professionally designed as well as the entrance and laundry rooms Large bonus room above the 3 car attachedheated garage allowing a getaway to watch movies or entertain This 5300 sq ft home is located on 26 acres with a 3 car attached garage a 2 car detached garage  Please allow 24 hours notice for viewings |Satellite Dish Microwave Freezer Window Coverings Garage door opener remotes Central Vacuum Stove|School Bus|Acreage Treed Rectangular Double width or more driveway|Deck|2 Level|2014|2014|Electric|5300 sqft|5pc Bathroom Bedroom Bedroom Bedroom Bedroom Laundry room Family room Games room Foyer Dining room 2pc Bathroom Laundry room Bedroom 5pc Bathroom Master bedroom Living room Kitchen|Second level Second level Second level Second level Second level Second level Second level Second level Main level Main level Main level Main level Main level Main level Main level Main level Main level|15 ft 2 in x 7 ft 11 ft x 11 ft 15 ft 6 in x 14 ft 1 in 14 ft 1 in x 14 ft 1 in 14 ft 1 in x 14 ft 1 in 3 ft 1 in x 5 ft 8 in 11 ft x 20 ft 21 ft 9 in x 38 ft 1 in 17 ft x 9 ft 15 ft 9 in x 11 ft 5 ft x 5 ft 9 ft 1 in x 5 ft 1 in 14 ft x 13 ft 6 in 20 ft 6 in x 10 ft 15 ft 9 in x 15 ft 9 in 15 ft 9 in x 18 ft 15 ft 9 in x 14 ft|26 ac|Lawn Underground sprinkler";
  IsResidential: "1";
  IsCommercial: "0";
};

declare interface Details {}

export interface ListingSchema {
  _id: string;
  ListingID: string;
  location: Geo;
  Address: string;
  City: string;
  HasAcreage: boolean;
  HasAirConditioning: "1";
  AmenitiesNearby?: number;
  Bathrooms: number;
  Bedrooms: number;
  BuildingAmenities?: number;
  BuildingType: number;
  BusinessType?: number;
  ClearCeilingHeight: string;
  Community: string;
  ConstructionStyle: string;
  Features: "1,42,126,256";
  HasFireplace: boolean;
  HasGarage: boolean;
  LandSizeMin: number;
  LandSizeMax: number;
  LeasePrice: null;
  LoadingType: null;
  ParkingSpaces: number;
  HasPool: boolean;
  SalePrice: string;
  PropertyType: "300";
  SizeExterior: null;
  SizeInterior: string;
  StoriesMin: string;
  StoriesMax: string;
  PropertyViewType: null;
  HasVirtualTour: boolean;
  HasWaterfront: boolean;
  ZoningType?: number;
  InsertedDate: string;
  ListingLastUpdated: string;
  PostalCode: string;
  CropType?: number;
  FarmType?: number;
  LivestockType?: number;
  LandUseType?: number;
  BusinessSubType?: number;
  UtilitiesAvailable?: number;
  IndividualIDs: number;
  Keywords: string;
  IsResidential: boolean;
  IsCommercial: boolean;
  details: Details;
}
export const Schema: object;
