type City implements Node {
  id: ID!
  _id: ID!
  city: String!
}

enum ScoreTypes {
  pedestrian_friendly
  transit_friendly
  car_friendly
  groceries
  primary_schools
  high_schools
  daycares
  parks
  restaurants
  cafes
  shopping
  nightlife
  quiet
  vibrant
  POP
  AGE
}

input Scores {
  key: ScoreTypes
  value: Int
}

extend type Query {
  uniqueCities: [City!]!
  findListing(id: ID!): [Listings!]!
  getAllListings: [Listings!]!
  listingBasedOnScores(scores: [Scores]): [Listings]
}
