type City implements Node {
  id: ID!
  _id: ID!
  city: String!
}

input Transportation {
  transit: Boolean!
  car: Boolean!
  pedestrian: Boolean!
}

input Leisure {
  cafe: Boolean!
  park: Boolean!
}

input Questions {
  bedrooms: Int!
  bathrooms: Int!
  pool: Boolean!
  leisure: Leisure!
  transportation: Transportation!
  kids: Boolean!
}

extend type Query {
  uniqueCities: [City!]!
  findListing(id: ID!): [Listings!]!
  getAllListings: [Listings!]!
  listings(answers: Questions!): [Listings]
}
