interface Median {
  INCOME: String
  SALE: String
  DELTA: String
}

interface Lifestyle {
  category: String
  scoreRatio: Float
}

interface Statistics {
  POP: Int
  Homes_Sold: Int
  Homes_Age: Int
  averageAge: Float
  median: Median
}

type Score @mongo(name: "enhancedLocationDetails") {
  _id: ID!
  DAUID: ID!
  statistics: Statistics
  lifestyle: Lifestyle
  listings: Listings @link(field: "ListingID")
}

type Query {
  scores(listings: ID!): Score
}
