enum Fields {
  VALUE
  TEXT
  DESCRIPTION
  CATEGORY
  NAME
}

enum Locale {
  EN
  FR
}

enum Category {
  Transportation
}

interface Attribute {
  type: String
  value: Float
  text: String
  description: String
  category: CATEGORY
}

interface Link {
  id: ID!
  paths: [String]
}


type Meta {
  nearby: [String!]!
  around: [String!]!
}

type Score {
  type: String
  attributes: [Attribute]
  links: Link
  meta: Meta
}

# {
#     lat: 45.5656,
#     lng: -73.5656,
#     include: 'transit_friendly,quiet',
#     fields: 'value,text,description,category,name',
#     locale: 'en'
#   }

extend type Query {
  score:
}
